# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170708_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_file', models.FileField(upload_to=b'content')),
                ('json_file', models.FileField(upload_to=b'content')),
            ],
        ),
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=b'ecar_files'),
        ),
        migrations.AddField(
            model_name='content',
            name='ekfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EkFile'),
        ),
    ]
