# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170712_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='folder_file',
        ),
    ]
