# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170712_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='json_file',
            field=models.FileField(upload_to=b'../content'),
        ),
    ]
