# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170712_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='json_file',
            field=models.FileField(upload_to=b'content'),
        ),
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=b'ecar_files'),
        ),
    ]
