# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170712_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='folder_file',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='content',
            name='json_file',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ekfile',
            name='file',
            field=models.FileField(upload_to=b''),
        ),
    ]
